Laboratorio 1

1. Vectores y Matrices

```{r}
#1.1 Vectores

student_1 <- c(50.4, 62.3, 92.1, 77.6, TRUE)
student_2 <- c(41.7, 87.9, 75.3, 72.4, FALSE)
student_3 <- c(30.3, 67.8, 69.3, 71.2, FALSE)
student_4 <- c(65.4, 85.1, 92.3, 96.8, TRUE)
student_5 <- c(70.4, 88.2, 95.2, 90.7, TRUE)


#1.2 Union de los vectores de estudiantes en un solo vector
students_vector <- c(student_1,student_2,student_3,student_4,student_5)
students_vector

#1.3 Construccion de la Matriz  tomando como datos el vector unificado anterior
students_matrix <- matrix(data=students_vector,byrow=TRUE, nrow=5)
students_matrix
```

2. Nombrado de una matriz

```{r}
#2.1
name_students <-  c("Lily Brown","Davis Moore", "Susan Taylor", "Mike Jones","Tom Hill")
name_courses_legal_age <-  c("TIC", "Accounting", "Psychology", "Ethics","Legal_age")

#2.2

#Nombamiento de columnas de la matriz
colnames(students_matrix) <- name_courses_legal_age

#Nombramiento de filas de la matriz
rownames(students_matrix) <- name_students

students_matrix

```

3. rowSums, cbind

```{r}
#3.1
#Sumatoria de punteos de los estudiantes, para todas las filas, y para 
# todas las columnas excepto la ultima 

total_grade_student <- rowSums(students_matrix[,1:4])
total_grade_student


#3.1 Agregando la columna de totales a la matriz
result_students <- cbind(students_matrix, total_grade_student)

result_students
```

4. Seleccionando elementos de una matriz

```{r}
# Seleccion de filas 1,3 y 5, Columnas 2 y 4
selected_elements <- result_students[c(1,3,5),c(2,4)]
selected_elements

```


5. Data frames


```{r}

students_grades_df <- data.frame(result_students)
students_grades_df

```
```{r}
#Subset con condicionales del dataframe original
subset(students_grades_df, subset=Accounting>80&Legal_age==TRUE)
```

6. Funciones, Condicionales y Bucles
```{r}


students_projection <- function(){
  
  for (i in 1:nrow(result_students)) {
    for(j in 1:(ncol(result_students)-2)){
      celdaValue <- result_students[i,j]
      
      if(celdaValue<=45){
        print(paste("Student at risk"))
      }else if(celdaValue>45&&celdaValue<61){
        print(paste("Student may be approved"))
      }else if(celdaValue>=61){
        print(paste("Student approved"))
      }
      
    }
  }
}

students_projection()

```
 
7. Data frames y lapply

```{r}
#7.1

index_education <- function(grade){
  (1+(grade/100))/2
}

#7.2
all_students_grade=students_grades_df[,1:4]

#7.3
lapply(all_students_grade, index_education)

```


8. Math utilities


```{r}
#Promedio por asignaturas

score_mean = sapply(students_grades_df[,1:4],mean)
score_mean
```

